module

public import Mathlib

/-!
# Six concyclic points satisfy the Euclidean Ramsey tensor criterion

A finite set `A ⊂ ℝ^d` is Euclidean Ramsey if for every number of colours some Euclidean space
contains a monochromatic congruent copy of `A` in every colouring with that many colours. The
main theorem of *A classification of finite Euclidean Ramsey configurations*
(openai/math, 2026, family 172) reads: a finite set of at least two points that affinely spans
`ℝ^d` is Ramsey if and only if it satisfies the tensor criterion `FieldCriterion` below, which
asks for a `(d+1) × (d+1)` matrix over `F ⊗_ℚ F` (`F` the field generated by the coordinates)
that annihilates every point in the left-right sandwich and multiplies to the identity on the
spatial block. The paper proves that every set of at most five points on a circle is Ramsey, and
the seven-point circle set of *A cyclic non-Ramsey heptagon* (arXiv:2609.23327) is not.

This repository proves, with the definitions restated character for character from
`lean/ComparatorChallenges/EuclideanRamsey.lean` of openai/math at commit
`adc7f1241b42e322a6451854ab7e4b4c146bf78a` (Apache-2.0; see `NOTICE`; the namespace is changed):

* every set of six distinct points on a circle satisfies `FieldCriterion`, by an explicit lift of
  the circle form through a product of two bilinear forms on the Veronese curve;
* every set of at most six distinct points on a circle, every spanning spherical set of at most six
  points in any dimension, and every spherical set of at most five points in any dimension
  satisfies `FieldCriterion`;
* the dimension theorem: every spherical set of at most `m + 4` distinct points, `m` the dimension
  of its affine span, satisfies `FieldCriterion` in its own space and field (so every spherical set
  of at most six points does, with any affine span; the two statements of the previous bullet are
  its special cases, kept from the first version); that `m + 5` points can fail for `m ≥ 2` is shown
  on paper in the accompanying note, not here;
* every spherical set whose coordinates are algebraic numbers satisfies `FieldCriterion`, and
  `FieldCriterion` always implies sphericity, so for algebraic coordinates the criterion is
  exactly sphericity;
* given the sufficiency half of the classification as a hypothesis, every spherical set of at most
  six points is Ramsey (so, with Theorem 1 of the heptagon paper, seven is the least size of a
  non-Ramsey spherical set, on paper), every spherical set of at most `m + 4` points is Ramsey, and
  every spanning spherical set with algebraic coordinates is Ramsey; given both halves, a spanning
  set with algebraic coordinates is Ramsey if and only if it is spherical.

The hypotheses `hsuff` and `hclass` are the sufficiency half and the full statement of the
classification, quantified exactly as `OAI.EuclideanRamsey.classification` is; the Ramsey
conclusions are conditional on them. This Mathlib-only file intentionally contains placeholders;
the corresponding Solution declarations are proved in a separate environment.
-/

@[expose] public section

namespace SixConcyclic

noncomputable section
open scoped TensorProduct

abbrev Space (d : ℕ) := EuclideanSpace ℝ (Fin d)

def Congruent {s d D : ℕ} (a : Fin s → Space d) (b : Fin s → Space D) : Prop :=
  ∀ i j, dist (b i) (b j) = dist (a i) (a j)

def Ramsey {s d : ℕ} (a : Fin s → Space d) : Prop :=
  ∀ r : ℕ, 2 ≤ r → ∃ D : ℕ, 1 ≤ D ∧
    ∀ c : Space D → Fin r, ∃ b : Fin s → Space D,
      Congruent a b ∧ ∃ k : Fin r, ∀ i, c (b i) = k

def coordinateField {s d : ℕ} (a : Fin s → Space d) : IntermediateField ℚ ℝ :=
  IntermediateField.adjoin ℚ (Set.range (fun ij : Fin s × Fin d => a ij.1 ij.2))

abbrev Coeff {s d : ℕ} (a : Fin s → Space d) := ↥(coordinateField a)
abbrev TensorRing {s d : ℕ} (a : Fin s → Space d) := Coeff a ⊗[ℚ] Coeff a

def coordinate {s d : ℕ} (a : Fin s → Space d) (i : Fin s) (j : Fin d) : Coeff a :=
  ⟨a i j, IntermediateField.subset_adjoin ℚ _ (Set.mem_range_self (i, j))⟩

def augmented {s d : ℕ} (a : Fin s → Space d) (i : Fin s) : Option (Fin d) → Coeff a
  | none => 1
  | some j => coordinate a i j

def multiply {s d : ℕ} (a : Fin s → Space d) : TensorRing a →ₐ[ℚ] Coeff a :=
  Algebra.TensorProduct.lmul' ℚ

def FieldCriterion {s d : ℕ} (a : Fin s → Space d) : Prop :=
  ∃ P : Matrix (Option (Fin d)) (Option (Fin d)) (TensorRing a),
    (∀ i : Fin s, ∑ α, ∑ β,
      ((augmented a i α) ⊗ₜ[ℚ] (1 : Coeff a)) * P α β *
      ((1 : Coeff a) ⊗ₜ[ℚ] (augmented a i β)) = 0) ∧
    (∀ α β : Fin d, multiply a (P (some α) (some β)) = if α = β then 1 else 0)

/-- Every set of six distinct points on a circle satisfies the tensor criterion. -/
theorem six_concyclic_fieldCriterion (a : Fin 6 → Space 2) (ha : Function.Injective a)
    (hsphere : ∃ c : Space 2, ∃ r : ℝ, ∀ i, dist (a i) c = r) : FieldCriterion a := by
  sorry

/-- Every set of at most six distinct points on a circle satisfies the tensor criterion. -/
theorem at_most_six_concyclic_fieldCriterion {s : ℕ} (a : Fin s → Space 2) (hs : s ≤ 6)
    (ha : Function.Injective a) (hsphere : ∃ c : Space 2, ∃ r : ℝ, ∀ i, dist (a i) c = r) :
    FieldCriterion a := by
  sorry

/-- Every spherical set of at most six distinct points that affinely spans its space satisfies
the tensor criterion. -/
theorem at_most_six_spherical_spanning_fieldCriterion {s d : ℕ} (a : Fin s → Space d)
    (hs : s ≤ 6) (ha : Function.Injective a) (hspan : affineSpan ℝ (Set.range a) = ⊤)
    (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r) : FieldCriterion a := by
  sorry

/-- Every spherical set of at most five distinct points, in any dimension, satisfies the tensor
criterion. -/
theorem at_most_five_spherical_fieldCriterion {s d : ℕ} (a : Fin s → Space d) (hs : s ≤ 5)
    (ha : Function.Injective a) (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r) :
    FieldCriterion a := by
  sorry

/-- Every spherical set whose coordinates are algebraic numbers satisfies the tensor criterion,
whatever its size: the separability idempotent of `F ⊗_ℚ F` lifts an `F`-rational sphere. -/
theorem algebraic_spherical_fieldCriterion {s d : ℕ} (a : Fin s → Space d)
    (halg : ∀ i j, IsAlgebraic ℚ (a i j))
    (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r) : FieldCriterion a := by
  sorry

/-- The tensor criterion implies sphericity: multiplying the certificate gives a sphere through
the points. -/
theorem fieldCriterion_spherical {s d : ℕ} (a : Fin s → Space d) (h : FieldCriterion a) :
    ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r := by
  sorry

/-- For algebraic coordinates the tensor criterion is exactly sphericity. -/
theorem algebraic_fieldCriterion_iff_spherical {s d : ℕ} (a : Fin s → Space d)
    (halg : ∀ i j, IsAlgebraic ℚ (a i j)) :
    FieldCriterion a ↔ ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r := by
  sorry

/-- Given the sufficiency half of the classification, every spherical set of at most six
distinct points, in any dimension and with any affine span, is Ramsey. -/
theorem at_most_six_spherical_ramsey_of_sufficiency
    (hsuff : ∀ {s d : ℕ} (a : Fin s → Space d), 2 ≤ s → 1 ≤ d → Function.Injective a →
      affineSpan ℝ (Set.range a) = ⊤ → FieldCriterion a → Ramsey a)
    {s d : ℕ} (a : Fin s → Space d) (hs : s ≤ 6) (ha : Function.Injective a)
    (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r) : Ramsey a := by
  sorry

/-- Given the sufficiency half of the classification, every set of at most six distinct points on
a circle is Ramsey. -/
theorem at_most_six_circle_points_ramsey_of_sufficiency
    (hsuff : ∀ {s d : ℕ} (a : Fin s → Space d), 2 ≤ s → 1 ≤ d → Function.Injective a →
      affineSpan ℝ (Set.range a) = ⊤ → FieldCriterion a → Ramsey a)
    {s : ℕ} (a : Fin s → Space 2) (hs : s ≤ 6) (ha : Function.Injective a)
    (hsphere : ∃ c : Space 2, ∃ r : ℝ, ∀ i, dist (a i) c = r) : Ramsey a := by
  sorry

/-- Given the sufficiency half of the classification, every spanning spherical set with algebraic
coordinates is Ramsey. -/
theorem algebraic_spherical_ramsey_of_sufficiency
    (hsuff : ∀ {s d : ℕ} (a : Fin s → Space d), 2 ≤ s → 1 ≤ d → Function.Injective a →
      affineSpan ℝ (Set.range a) = ⊤ → FieldCriterion a → Ramsey a)
    {s d : ℕ} (a : Fin s → Space d) (hs : 2 ≤ s) (hd : 1 ≤ d) (ha : Function.Injective a)
    (hspan : affineSpan ℝ (Set.range a) = ⊤) (halg : ∀ i j, IsAlgebraic ℚ (a i j))
    (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r) : Ramsey a := by
  sorry

/-- Given the classification, a spanning set with algebraic coordinates is Ramsey if and only if
it is spherical. -/
theorem algebraic_ramsey_iff_spherical_of_classification
    (hclass : ∀ {s d : ℕ} (a : Fin s → Space d), 2 ≤ s → 1 ≤ d → Function.Injective a →
      affineSpan ℝ (Set.range a) = ⊤ → (Ramsey a ↔ FieldCriterion a))
    {s d : ℕ} (a : Fin s → Space d) (hs : 2 ≤ s) (hd : 1 ≤ d) (ha : Function.Injective a)
    (hspan : affineSpan ℝ (Set.range a) = ⊤) (halg : ∀ i j, IsAlgebraic ℚ (a i j)) :
    Ramsey a ↔ ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r := by
  sorry

/-- The dimension theorem: every spherical set of at most `m + 4` distinct points, where
`m` is the dimension of its affine span, satisfies the tensor criterion, in its own space and
coordinate field. -/
theorem spherical_fieldCriterion_of_card_le_finrank_add_four {s d : ℕ} (a : Fin s → Space d)
    (ha : Function.Injective a) (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r)
    (hdim : s ≤ Module.finrank ℝ (vectorSpan ℝ (Set.range a)) + 4) : FieldCriterion a := by
  sorry

/-- Every spherical set of at most six distinct points, in any dimension and with any affine
span, satisfies the tensor criterion. -/
theorem at_most_six_spherical_fieldCriterion {s d : ℕ} (a : Fin s → Space d) (hs : s ≤ 6)
    (ha : Function.Injective a) (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r) :
    FieldCriterion a := by
  sorry

/-- Given the sufficiency half of the classification, every spherical set of at most `m + 4`
distinct points, `m` the dimension of its affine span, is Ramsey. -/
theorem spherical_ramsey_of_sufficiency_of_card_le_finrank_add_four
    (hsuff : ∀ {s d : ℕ} (a : Fin s → Space d), 2 ≤ s → 1 ≤ d → Function.Injective a →
      affineSpan ℝ (Set.range a) = ⊤ → FieldCriterion a → Ramsey a)
    {s d : ℕ} (a : Fin s → Space d) (ha : Function.Injective a)
    (hsphere : ∃ c : Space d, ∃ r : ℝ, ∀ i, dist (a i) c = r)
    (hdim : s ≤ Module.finrank ℝ (vectorSpan ℝ (Set.range a)) + 4) : Ramsey a := by
  sorry

end

end SixConcyclic

end
