"""Certificate 0003: the separability idempotent at work on an algebraic circle.

Standard library only; exact arithmetic over fractions.Fraction; no assert statements.

Field and tensor ring. F = Q(sqrt 2), an element a + b sqrt 2 stored as (a, b).
B = F (x)_Q F = Q[x, y] / (x^2 - 2, y^2 - 2), basis 1, x, y, xy (x = sqrt2 (x) 1,
y = 1 (x) sqrt2). Left lift L(a + b sqrt2) = a + b x, right lift R = a + b y.
Multiplication m: B -> F sends x and y to sqrt 2.

Idempotent. e = (1 + xy/2)/2 satisfies m(e) = 1, e (x - y) = 0 and e^2 = e. Since F is
generated by sqrt 2, e L(f) = e R(f) for every f in F, so for any spherical configuration with
coordinates in F and circle form S over F, P = e L(S) satisfies every evaluation identity
(e L(p~^T S p~) = 0) and m(P) = S.

Configuration. Nine points on the circle with centre o = (1/3 + sqrt2, -2 sqrt2) and radius
rho = 1 + sqrt2, from stereographic parameters t in Q(sqrt2): o + rho ((1 - t^2), 2t)/(1 + t^2).

Checks: the points are on the circle and distinct; m(e) = 1, e (x - y) = 0, e^2 = e; P passes all
evaluations and has spatial block I for the first 6, 7 and all 9 points. Extension: the
universal six-point construction of certificate 0001, run in this B (which is not a domain),
also passes at the first six points.
Forged controls (expected to FAIL): the naive lift L(S) fails the evaluations; the complementary
idempotent (1 - xy/2)/2 fails the multiplication condition.
"""
import sys
import itertools
from fractions import Fraction as Fr

FAILURES = []


def check(ok, msg):
    if ok:
        print("  ok   " + msg)
    else:
        print("  FAIL " + msg)
        FAILURES.append(msg)


# ---------------------------------------------------------------- F = Q(sqrt 2)
class F:
    __slots__ = ("a", "b")

    def __init__(self, a, b=0):
        self.a, self.b = Fr(a), Fr(b)

    def __add__(self, o):
        o = fl(o)
        return F(self.a + o.a, self.b + o.b)

    __radd__ = __add__

    def __neg__(self):
        return F(-self.a, -self.b)

    def __sub__(self, o):
        return self + (-fl(o))

    def __rsub__(self, o):
        return fl(o) - self

    def __mul__(self, o):
        o = fl(o)
        return F(self.a * o.a + 2 * self.b * o.b, self.a * o.b + self.b * o.a)

    __rmul__ = __mul__

    def inv(self):
        n = self.a * self.a - 2 * self.b * self.b      # nonzero for a nonzero element (sqrt 2 irrational)
        if n == 0:
            raise ZeroDivisionError("inverse of 0 in Q(sqrt2)")
        return F(self.a / n, -self.b / n)

    def __truediv__(self, o):
        return self * fl(o).inv()

    def __eq__(self, o):
        o = fl(o)
        return self.a == o.a and self.b == o.b

    def __hash__(self):
        return hash((self.a, self.b))

    def __repr__(self):
        return "%s + %s*sqrt2" % (self.a, self.b)


def fl(o):
    return o if isinstance(o, F) else F(o)


S2 = F(0, 1)


# ---------------------------------------------------------------- B = Q[x,y]/(x^2-2, y^2-2)
class B:
    """c[(i, j)] is the coefficient of x^i y^j, i, j in {0, 1}."""
    __slots__ = ("c",)

    def __init__(self, c=None):
        self.c = {k: Fr(0) for k in itertools.product((0, 1), repeat=2)}
        if c:
            for k, v in c.items():
                self.c[k] += Fr(v)

    def __add__(self, o):
        o = bl(o)
        return B({k: self.c[k] + o.c[k] for k in self.c})

    __radd__ = __add__

    def __neg__(self):
        return B({k: -v for k, v in self.c.items()})

    def __sub__(self, o):
        return self + (-bl(o))

    def __rsub__(self, o):
        return bl(o) - self

    def __mul__(self, o):
        o = bl(o)
        r = {k: Fr(0) for k in self.c}
        for (i1, j1), v1 in self.c.items():
            if v1 == 0:
                continue
            for (i2, j2), v2 in o.c.items():
                if v2 == 0:
                    continue
                i, j, f = i1 + i2, j1 + j2, v1 * v2
                if i == 2:
                    i, f = 0, 2 * f
                if j == 2:
                    j, f = 0, 2 * f
                r[(i, j)] += f
        return B(r)

    __rmul__ = __mul__

    def is_zero(self):
        return all(v == 0 for v in self.c.values())

    def __eq__(self, o):
        return (self - bl(o)).is_zero()

    def __hash__(self):
        return id(self)


def bl(o):
    if isinstance(o, B):
        return o
    if isinstance(o, F):
        raise TypeError("lift an F element with L or R")
    return B({(0, 0): o})


def L(f):
    f = fl(f)
    return B({(0, 0): f.a, (1, 0): f.b})


def R(f):
    f = fl(f)
    return B({(0, 0): f.a, (0, 1): f.b})


def mult(z):
    """m: x, y -> sqrt 2."""
    return F(z.c[(0, 0)] + 2 * z.c[(1, 1)], z.c[(1, 0)] + z.c[(0, 1)])


X, Y = B({(1, 0): 1}), B({(0, 1): 1})


# ---------------------------------------------------------------- the configuration
o = (F(Fr(1, 3), 1), F(0, -2))
rho = F(1, 1)
rho2 = rho * rho


def stereo(t):
    t = fl(t)
    d = (1 + t * t).inv()
    return ((1 - t * t) * d, 2 * t * d)


tl = [S2, F(1, 1), F(Fr(1, 2), -1), F(-2, 3), F(-1), F(Fr(2, 7), 2), F(5, -1), F(0, -3), F(Fr(9, 4))]
pts = []
for t in tl:
    s = stereo(t)
    pts.append((o[0] + rho * s[0], o[1] + rho * s[1]))
print("the nine points")
check(all((p[0] - o[0]) * (p[0] - o[0]) + (p[1] - o[1]) * (p[1] - o[1]) == rho2 for p in pts),
      "all nine points lie on the circle |p - o|^2 = (1 + sqrt2)^2")
check(len({(p[0], p[1]) for p in pts}) == 9, "the nine points are distinct")

S = [[o[0] * o[0] + o[1] * o[1] - rho2, -o[0], -o[1]], [-o[0], F(1), F(0)], [-o[1], F(0), F(1)]]
check(all(sum((pa * S[a][b] * pb for a, pa in enumerate((F(1),) + p) for b, pb in enumerate((F(1),) + p)), F(0)) == 0
          for p in pts), "the circle form S over F vanishes at every point")


def evalP(P, p):
    pl = [B({(0, 0): 1}), L(p[0]), L(p[1])]
    pr = [B({(0, 0): 1}), R(p[0]), R(p[1])]
    tot = B()
    for a in range(3):
        for b in range(3):
            tot = tot + pl[a] * P[a][b] * pr[b]
    return tot


def spatial_I(P):
    return all(mult(P[a][b]) == (1 if a == b else 0) for a in (1, 2) for b in (1, 2))


print("the idempotent")
e = (1 + X * Y * B({(0, 0): Fr(1, 2)})) * B({(0, 0): Fr(1, 2)})
check(mult(e) == 1, "m(e) = 1")
check((e * (X - Y)).is_zero(), "e (x - y) = 0")
check(e * e == e, "e^2 = e")
check(all(e * L(f) == e * R(f) for p in pts for f in p), "e L(f) = e R(f) for every coordinate f")

print("the certificate P = e L(S)")
Pe = [[e * L(S[a][b]) for b in range(3)] for a in range(3)]
for n in (6, 7, 9):
    ev = all(evalP(Pe, p).is_zero() for p in pts[:n])
    check(ev and spatial_I(Pe), "first %d points: every evaluation is 0 in B, spatial block of m(P) is I" % n)
mPe = [[mult(Pe[a][b]) for b in range(3)] for a in range(3)]
check(all(mPe[a][b] == S[a][b] for a in range(3) for b in range(3)), "m(P) = S")

print("forged controls")
Pn = [[L(S[a][b]) for b in range(3)] for a in range(3)]
naive_passes = all(evalP(Pn, p).is_zero() for p in pts[:6]) and spatial_I(Pn)
print("  naive lift L(S) passes: %s (expected False)" % naive_passes)
check(not naive_passes, "forged control 1 (naive lift L(S)) is rejected")
e2 = (1 - X * Y * B({(0, 0): Fr(1, 2)})) * B({(0, 0): Fr(1, 2)})
Pe2 = [[e2 * L(S[a][b]) for b in range(3)] for a in range(3)]
comp_ev = all(evalP(Pe2, p).is_zero() for p in pts)
comp_passes = comp_ev and spatial_I(Pe2)
print("  complementary idempotent: evaluations zero = %s, spatial block I = %s; passes: %s (expected False)"
      % (comp_ev, spatial_I(Pe2), comp_passes))
check(not comp_passes, "forged control 2 (complementary idempotent) is rejected")


# ---------------------------------------------------------------- extension: the six-point construction in B
def det(M, zero):
    n = len(M)
    total = zero
    for perm in itertools.permutations(range(n)):
        inv = sum(1 for a in range(n) for b in range(a + 1, n) if perm[a] > perm[b])
        term = M[0][perm[0]]
        for r in range(1, n):
            term = term * M[r][perm[r]]
        total = total - term if inv % 2 else total + term
    return total


print("extension: the universal six-point construction (certificate 0001) in this B")
P6 = pts[:6]
base = P6[5]
ev_ = (base[0] - o[0], base[1] - o[1])
dirs = [(P6[j][0] - base[0], P6[j][1] - base[1]) for j in range(5)] + [(-ev_[1], ev_[0])]
Lam = [[F(1), F(0), F(1)],
       [base[0] - 2 * ev_[0], -2 * ev_[1], base[0]],
       [base[1], -2 * ev_[0], base[1] - 2 * ev_[1]]]
dL = det(Lam, F(0))
check(dL == 4 * rho2, "det Lambda = 4 rho^2")
adj = [[None] * 3 for _ in range(3)]
for i in range(3):
    for j in range(3):
        minor = [[Lam[r][c] for c in range(3) if c != j] for r in range(3) if r != i]
        adj[j][i] = det(minor, F(0)) * ((-1) ** (i + j))
Linv = [[adj[i][j] / dL for j in range(3)] for i in range(3)]


def ell_coeffs(S_):
    rows = [[L(dirs[j][0]) * R(dirs[j][0]), L(dirs[j][0]) * R(dirs[j][1]),
             L(dirs[j][1]) * R(dirs[j][0]), L(dirs[j][1]) * R(dirs[j][1])] for j in S_]
    out = []
    for k in range(4):
        M = [[rw[cc] for cc in range(4) if cc != k] for rw in rows]
        d = det(M, B())
        out.append(d if k % 2 == 0 else -d)
    return out


xw, yw = [0, 0, 1, 1], [0, 1, 0, 1]
c1, c2 = ell_coeffs([0, 1, 2]), ell_coeffs([3, 4, 5])
Q = [[B() for _ in range(3)] for _ in range(3)]
for k in range(4):
    for l in range(4):
        Q[xw[k] + xw[l]][yw[k] + yw[l]] = Q[xw[k] + xw[l]][yw[k] + yw[l]] + c1[k] * c2[l]
cval = mult(Q[0][2])
check(not (cval == 0), "the bracket constant c = m(Q_02) is nonzero")
kappa = -2 * rho2
sc = L(kappa / cval)
P = [[sc * sum((L(Linv[a1][a]) * Q[a1][b1] * R(Linv[b1][b]) for a1 in range(3) for b1 in range(3)), B())
      for b in range(3)] for a in range(3)]
ok6 = all(evalP(P, p).is_zero() for p in P6)
mP = [[mult(P[a][b]) for b in range(3)] for a in range(3)]
check(ok6, "six-point construction: all six evaluations are 0 in B")
check(all(mP[a][b] == S[a][b] for a in range(3) for b in range(3)), "six-point construction: m(P) = S (spatial block I)")
seventh = evalP(P, pts[6]).is_zero()
print("  (the six-point P is not built for the seventh point; its evaluation there is zero: %s)" % seventh)

print("")
print("forged control 1 (naive lift): %s (expected FAIL)" % ("PASS" if naive_passes else "FAIL"))
print("forged control 2 (complementary idempotent): %s (expected FAIL)" % ("PASS" if comp_passes else "FAIL"))
if FAILURES:
    print("%d check(s) failed" % len(FAILURES))
    print("VERDICT: FAIL")
    sys.exit(1)
print("VERDICT: PASS")
